# Generated by Django 5.2.4 on 2025-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="emp_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
